# Project Manager Pro v3.0 - Docker Compose
version: '3.8'

services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: projectmanager_db
    environment:
      SA_PASSWORD: 'ProjectManager123!'
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'Express'
    ports:
      - '1433:1433'
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - projectmanager_network
    restart: unless-stopped
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "ProjectManager123!" -Q "SELECT 1"
      interval: 30s
      timeout: 10s
      retries: 5

  # Project Manager Application
  app:
    build: .
    container_name: projectmanager_app
    ports:
      - '8501:8501'
    environment:
      - DB_SERVER=sqlserver
      - DB_DATABASE=ProjectManagerDB
      - DB_USERNAME=sa
      - DB_PASSWORD=ProjectManager123!
      - DB_DRIVER=ODBC Driver 17 for SQL Server
      - DB_PORT=1433
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - projectmanager_network
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:8501/_stcore/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads

  # Redis Cache (Optional)
  redis:
    image: redis:7-alpine
    container_name: projectmanager_redis
    ports:
      - '6379:6379'
    networks:
      - projectmanager_network
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    container_name: projectmanager_nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - projectmanager_network
    restart: unless-stopped

# Networks
networks:
  projectmanager_network:
    driver: bridge

# Volumes
volumes:
  sqlserver_data:
    driver: local
  redis_data:
    driver: local
