# docker-compose.override.yml (Development)
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/.streamlit
    environment:
      - STREAMLIT_SERVER_RUNONFORKPYSQLITE3=true
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=poll
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0 --server.fileWatcherType=poll
