# config/app_config.yaml
# DENSO Project Manager Pro - Application Configuration

app:
  app_name: 'DENSO Project Manager Pro'
  version: '2.0.0'
  debug: false
  log_level: 'INFO'
  environment: 'development'
  max_upload_size_mb: 50
  session_timeout: 3600
  timezone: 'Asia/Bangkok'
  language: 'th'

database:
  driver: 'ODBC Driver 17 for SQL Server'
  connection_timeout: 30
  command_timeout: 60
  encrypt: 'yes'
  trust_server_certificate: 'yes'
  pool_size: 10
  pool_timeout: 30
  pool_recycle: 3600

security:
  bcrypt_rounds: 12
  max_login_attempts: 5
  lockout_duration: 900
  password_min_length: 8
  session_cookie_secure: false
  session_cookie_httponly: true
  session_cookie_samesite: 'strict'

  # Token expiry settings (in respective units)
  access_token_expiry_minutes: 60
  refresh_token_expiry_days: 7
  password_reset_token_expiry_hours: 1
  remember_me_expiry_days: 30

  # Password policy
  password_require_uppercase: true
  password_require_lowercase: true
  password_require_digits: true
  password_require_special: true
  password_history_count: 5

cache:
  redis_enabled: false
  redis_host: 'localhost'
  redis_port: 6379
  redis_password: ''
  max_memory_mb: 100
  default_ttl_seconds: 3600

  # Cache strategies
  user_session_ttl: 3600
  project_data_ttl: 1800
  analytics_data_ttl: 900
  file_metadata_ttl: 7200

features:
  enable_notifications: true
  enable_file_upload: true
  enable_analytics: true
  enable_performance_monitoring: true
  enable_audit_log: true
  enable_backup: true
  enable_realtime_updates: true
  enable_dark_mode: true
  enable_mobile_view: true

email:
  smtp_server: 'smtp.gmail.com'
  smtp_port: 587
  smtp_username: ''
  smtp_password: ''
  from_email: 'noreply@denso.com'
  from_name: 'DENSO Project Manager'
  enable_ssl: true
  timeout: 30

  # Email templates
  password_reset_template: 'password_reset.html'
  welcome_template: 'welcome.html'
  notification_template: 'notification.html'

logging:
  level: 'INFO'
  file_path: 'logs/app.log'
  max_file_size_mb: 10
  backup_count: 5
  enable_console: true

  # Log formats
  file_format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  console_format: '%(levelname)s - %(message)s'

  # Logger configurations
  loggers:
    database: 'INFO'
    security: 'WARNING'
    performance: 'INFO'
    api: 'DEBUG'

performance:
  enable_monitoring: true
  page_load_threshold: 2.0
  memory_threshold_mb: 512
  db_query_threshold: 1.0
  cache_hit_rate_threshold: 80.0

  # Performance optimizations
  enable_gzip: true
  enable_caching: true
  max_concurrent_requests: 100
  request_timeout: 30

ui:
  theme: 'light'
  enable_animations: true
  enable_glassmorphism: true
  default_page_size: 20
  compact_mode: false

  # Theme colors
  primary_color: '#667eea'
  secondary_color: '#764ba2'
  success_color: '#10b981'
  warning_color: '#f59e0b'
  error_color: '#ef4444'

  # Layout settings
  sidebar_width: 300
  header_height: 60
  footer_height: 40

notifications:
  enable_notifications: true
  check_interval: 300
  max_notifications_per_user: 50
  default_priority: 'medium'

  # Notification types
  enable_email_notifications: true
  enable_browser_notifications: true
  enable_slack_notifications: false
  enable_teams_notifications: false

  # Auto-dismiss settings
  auto_dismiss_info: 5000
  auto_dismiss_success: 3000
  auto_dismiss_warning: 8000
  auto_dismiss_error: 10000

backup:
  enable_auto_backup: true
  backup_interval_hours: 24
  backup_retention_days: 30
  backup_location: 'backups/'
  backup_compression: true

  # Backup types
  enable_database_backup: true
  enable_file_backup: true
  enable_config_backup: true

analytics:
  enable_analytics: true
  data_retention_days: 365
  enable_real_time_analytics: true

  # Analytics providers
  enable_google_analytics: false
  google_analytics_id: ''

  # Custom analytics
  track_user_actions: true
  track_performance_metrics: true
  track_error_events: true

api:
  enable_api: true
  api_version: 'v1'
  rate_limit_per_minute: 60
  enable_api_docs: true

  # API security
  require_api_key: true
  enable_cors: false
  allowed_origins: []

file_upload:
  max_file_size_mb: 50
  allowed_extensions:
    [
      '.jpg',
      '.jpeg',
      '.png',
      '.gif',
      '.pdf',
      '.doc',
      '.docx',
      '.xls',
      '.xlsx',
      '.ppt',
      '.pptx',
      '.txt',
      '.csv',
    ]
  upload_path: 'uploads/'
  enable_virus_scan: false

  # Image processing
  enable_image_resize: true
  max_image_width: 1920
  max_image_height: 1080
  image_quality: 85

integration:
  # External integrations
  enable_slack: false
  slack_webhook_url: ''

  enable_teams: false
  teams_webhook_url: ''

  enable_jira: false
  jira_url: ''
  jira_username: ''
  jira_api_token: ''

  enable_github: false
  github_token: ''
