# .streamlit/secrets.toml
# Database Configuration
[database]
server = "10.73.148.27"
database = "ProjectManagerDB"
username = "TS00029"
password = "Thammaphon@TS00029"
driver = "ODBC Driver 17 for SQL Server"
port = "1433"
timeout = "30"
connection_timeout = "30"

# Application Configuration
[app]
secret_key = "your-secret-key-here-change-in-production"
session_timeout = 3600  # 1 hour
debug_mode = true  # Set to true for development
log_level = "INFO"

# Security Configuration
[security]
password_min_length = 8
password_complexity = true
max_login_attempts = 5
lockout_duration = 1800  # 30 minutes
jwt_secret = "your-jwt-secret-here-change-in-production"

# Email Configuration (Optional)
[email]
smtp_server = "smtp.gmail.com"
smtp_port = 587
smtp_username = "your-email@gmail.com"
smtp_password = "your-app-password"
sender_name = "Project Manager Pro"
sender_email = "noreply@yourcompany.com"

# File Upload Configuration
[upload]
max_file_size = 10  # MB
allowed_extensions = [".pdf", ".docx", ".xlsx", ".png", ".jpg", ".jpeg"]
upload_folder = "./uploads"

# Performance Configuration
[performance]
cache_ttl = 300  # 5 minutes
max_concurrent_users = 100
request_timeout = 30

# Redis Configuration (Optional)
[redis]
host = "localhost"
port = 6379
db = 0
password = ""

# Development Configuration
[development]
hot_reload = true
show_debug_info = true  # Set to true for development
mock_database = false