[database]
server = "10.73.148.27"
database = "ProjectManagerDB" 
username = "TS00029"
password = "Thammaphon@TS00029"

[app]
debug = true
session_timeout = 3600

[security]
bcrypt_rounds = 12
max_login_attempts = 5