# .streamlit/secrets.toml

[database]
# Primary database connection
type = "sqlite"  # Options: "sqlite", "sqlserver", "postgresql", "mysql"

# SQLite configuration (for development/small deployments)
sqlite_path = "data/sdx_project_manager.db"
sqlite_timeout = 30
sqlite_check_same_thread = false

# SQL Server configuration (for enterprise deployments)
sqlserver_server = "10.73.148.27"
sqlserver_database = "SDXProjectManager"
sqlserver_username = "TS00029"
sqlserver_password = "Thammaphon@TS00029"
sqlserver_driver = "ODBC Driver 18 for SQL Server"
sqlserver_port = 1433
sqlserver_encrypt = true
sqlserver_trust_server_certificate = false
sqlserver_connection_timeout = 30
sqlserver_command_timeout = 60

# PostgreSQL configuration (alternative enterprise option)
postgresql_host = "your-postgres-host"
postgresql_port = 5432
postgresql_database = "sdx_project_manager"
postgresql_username = "your-username"
postgresql_password = "your-password"
postgresql_sslmode = "require"

# MySQL configuration (alternative option)
mysql_host = "your-mysql-host"
mysql_port = 3306
mysql_database = "sdx_project_manager"
mysql_username = "your-username"
mysql_password = "your-password"
mysql_charset = "utf8mb4"
mysql_ssl_disabled = false

# Connection pooling settings
pool_size = 10
max_overflow = 20
pool_timeout = 30
pool_recycle = 3600
pool_pre_ping = true

# =============================================================================
# Email Configuration
# =============================================================================

[email]
# SMTP server settings
smtp_host = "smtp.office365.com"  # Or your SMTP server
smtp_port = 587
smtp_username = "noreply@denso-innovation.com"
smtp_password = "your-email-password"
smtp_use_tls = true
smtp_use_ssl = false

# Email settings
from_email = "noreply@denso-innovation.com"
from_name = "SDX Project Manager"
reply_to = "support@denso-innovation.com"

# Email templates
admin_email = "admin@denso-innovation.com"
support_email = "support@denso-innovation.com"

# =============================================================================
# Security Configuration
# =============================================================================

[security]
# Application secrets
secret_key = "your-secret-key-here-make-it-long-and-random"
jwt_secret = "your-jwt-secret-key"
encryption_key = "your-encryption-key-32-chars-long"

# Session configuration
session_lifetime = 1440  # minutes (24 hours)
remember_me_duration = 10080  # minutes (7 days)
max_login_attempts = 5
lockout_duration = 30  # minutes

# Password policy
password_min_length = 8
password_require_uppercase = true
password_require_lowercase = true
password_require_numbers = true
password_require_special = true
password_history_count = 5

# =============================================================================
# External API Keys
# =============================================================================

[apis]
# Third-party service API keys
openai_api_key = "your-openai-api-key"  # For AI features
mapbox_api_key = "your-mapbox-key"  # For location features
sendgrid_api_key = "your-sendgrid-key"  # Alternative email service
slack_webhook_url = "your-slack-webhook"  # For notifications
teams_webhook_url = "your-teams-webhook"  # For notifications

# Cloud storage (if using)
aws_access_key_id = "your-aws-access-key"
aws_secret_access_key = "your-aws-secret-key"
aws_region = "ap-southeast-1"
aws_s3_bucket = "your-s3-bucket"

azure_storage_account = "your-azure-account"
azure_storage_key = "your-azure-key"
azure_container = "your-container"

# =============================================================================
# Integration Credentials
# =============================================================================

[integrations]
# Microsoft Graph (for Office 365 integration)
microsoft_client_id = "your-microsoft-client-id"
microsoft_client_secret = "your-microsoft-client-secret"
microsoft_tenant_id = "your-microsoft-tenant-id"
microsoft_redirect_uri = "http://localhost:8501/auth/callback"

# Google Workspace (for Google integration)
google_client_id = "your-google-client-id"
google_client_secret = "your-google-client-secret"
google_project_id = "your-google-project-id"

# JIRA integration
jira_url = "https://your-company.atlassian.net"
jira_username = "your-jira-email"
jira_api_token = "your-jira-api-token"

# GitHub integration
github_token = "your-github-personal-access-token"
github_org = "your-github-organization"

# GitLab integration
gitlab_url = "https://gitlab.com"
gitlab_token = "your-gitlab-access-token"
gitlab_project_id = "your-project-id"

# Slack integration
slack_bot_token = "xoxb-your-slack-bot-token"
slack_signing_secret = "your-slack-signing-secret"
slack_app_token = "xapp-your-slack-app-token"

# Microsoft Teams integration
teams_app_id = "your-teams-app-id"
teams_app_password = "your-teams-app-password"

# =============================================================================
# Monitoring and Analytics
# =============================================================================

[monitoring]
# Application monitoring
sentry_dsn = "your-sentry-dsn"  # For error tracking
newrelic_license_key = "your-newrelic-key"  # For performance monitoring
datadog_api_key = "your-datadog-key"  # For infrastructure monitoring

# Analytics
google_analytics_id = "GA-XXXXXXXXX"
mixpanel_token = "your-mixpanel-token"
amplitude_api_key = "your-amplitude-key"

# =============================================================================
# Backup and Storage
# =============================================================================

[backup]
# Backup storage
backup_encryption_key = "your-backup-encryption-key"
backup_location = "data/backups"  # Local path or cloud URL

# Cloud backup settings
backup_to_cloud = false
cloud_provider = "aws"  # Options: "aws", "azure", "gcp"

# AWS backup settings
aws_backup_bucket = "your-backup-bucket"
aws_backup_region = "ap-southeast-1"

# Azure backup settings
azure_backup_account = "your-backup-account"
azure_backup_container = "backups"

# =============================================================================
# License and Compliance
# =============================================================================

[license]
# Software licenses
license_key = "your-enterprise-license-key"
organization = "DENSO Innovation Co., Ltd."
max_users = 1000
expiry_date = "2025-12-31"
features = ["analytics", "integrations", "backup", "sso"]

# Compliance settings
gdpr_enabled = true
data_retention_days = 2555  # 7 years
audit_retention_days = 365

# =============================================================================
# Development and Testing
# =============================================================================

[development]
# Development database (separate from production)
dev_database_url = "sqlite:///data/dev_sdx.db"
test_database_url = "sqlite:///data/test_sdx.db"

# Development API keys (usually different from production)
dev_email_backend = "console"  # For testing emails
dev_storage_backend = "local"  # For testing file uploads

# Debug settings
debug_mode = false
enable_sql_logging = false
mock_external_apis = false

# =============================================================================
# Load Balancing and Clustering
# =============================================================================

[cluster]
# Multi-instance deployment
instance_id = "sdx-instance-01"
cluster_secret = "your-cluster-secret"
redis_url = "redis://your-redis-server:6379/0"
session_store = "redis"  # Options: "memory", "redis", "database"

# Load balancer settings
sticky_sessions = true
health_check_endpoint = "/health"
health_check_interval = 30

# =============================================================================
# Logging and Audit
# =============================================================================

[logging]
# Centralized logging
log_level = "INFO"
log_format = "json"
log_output = "file"  # Options: "console", "file", "syslog", "cloud"

# Cloud logging
cloudwatch_log_group = "sdx-project-manager"
azure_log_workspace = "your-log-workspace"
gcp_log_project = "your-gcp-project"

# Audit logging
audit_log_enabled = true
audit_log_location = "logs/audit"
audit_log_encryption = true

# =============================================================================
# Custom Environment Variables
# =============================================================================

[environment]
# Environment-specific settings
APP_ENV = "production"  # Options: "development", "staging", "production"
TZ = "Asia/Bangkok"
LANG = "th_TH.UTF-8"

# Feature flags
FEATURE_AI_ASSISTANT = true
FEATURE_ADVANCED_ANALYTICS = true
FEATURE_SSO = true
FEATURE_API = true
FEATURE_MOBILE_APP = false

# Performance tuning
MAX_WORKERS = 4
WORKER_TIMEOUT = 30
KEEPALIVE = 2
MAX_REQUESTS = 1000
MAX_REQUESTS_JITTER = 50

# =============================================================================
# Example Configuration for Different Environments
# =============================================================================

# Uncomment and modify based on your deployment environment

# [production]
# database_type = "sqlserver"
# database_server = "prod-sql-server.database.windows.net"
# email_backend = "smtp"
# storage_backend = "azure"
# cache_backend = "redis"
# session_store = "redis"
# debug_mode = false

# [staging]
# database_type = "sqlserver"
# database_server = "staging-sql-server.database.windows.net"
# email_backend = "smtp"
# storage_backend = "local"
# cache_backend = "memory"
# session_store = "database"
# debug_mode = true

# [development]
# database_type = "sqlite"
# database_path = "data/dev_sdx.db"
# email_backend = "console"
# storage_backend = "local"
# cache_backend = "memory"
# session_store = "memory"
# debug_mode = true