# .streamlit/secrets.toml
# DENSO Project Manager Pro - Secrets Configuration

[database]
server = "10.73.148.27"
database = "ProjectManagerDB" 
username = "TS00029"
password = "Thammaphon@TS00029"
driver = "ODBC Driver 17 for SQL Server"

[database.connection_options]
encrypt = "yes"
trust_server_certificate = "yes"
connection_timeout = 30
command_timeout = 60

[app]
# Main application secret key
secret_key = "xvQR8YkZP9mF3nB7sL4tW6jK8mN2pQ5rT7yU9vX1cZ3dF6gH9jL2mP5s"
debug = false
log_level = "INFO"
session_timeout = 3600
max_upload_size = 50
timezone = "Asia/Bangkok"
language = "th"

[security]
# Authentication & Session Security
bcrypt_rounds = 12
max_login_attempts = 5
lockout_duration = 900
password_min_length = 8
session_cookie_secure = true
session_cookie_httponly = true
session_cookie_samesite = "strict"

# Token Management Keys (แยกตาม purpose)
password_reset_key = "mF3nB7sL4tW6jK8mN2pQ5rT7yU9vX1cZ3xvQR8YkZP9hG4jM7nQ0s"
jwt_access_key = "sL4tW6jK8mN2pQ5rT7yU9vX1cZ3xvQR8YkZP9mF3nB7gH0jM4nQ7s"
jwt_refresh_key = "jK8mN2pQ5rT7yU9vX1cZ3xvQR8YkZP9mF3nB7sL4tW6gH9jM2nQ5s"
csrf_secret = "8mN2pQ5rT7yU9vX1cZ3xvQR8YkZP"
data_encryption_key = "W6jK8mN2pQ5rT7yU9vX1cZ3xvQR8YkZP9mF3nB7sL4tgH7jM0nQ3s"

# Token Expiry Settings
access_token_expiry_minutes = 60
refresh_token_expiry_days = 7
password_reset_token_expiry_hours = 1
remember_me_expiry_days = 30

[features]
enable_notifications = true
enable_file_upload = true
enable_analytics = true
enable_performance_monitoring = true
enable_audit_log = true
enable_backup = true

[email]
# Email configuration for notifications
smtp_server = "smtp.gmail.com"
smtp_port = 587
smtp_username = "noreply@denso.com"
smtp_password = ""
from_email = "noreply@denso.com"
enable_ssl = true

[cache]
redis_enabled = false
redis_host = "localhost"
redis_port = 6379
redis_password = ""
max_memory_mb = 100
default_ttl_seconds = 3600

[logging]
level = "INFO"
file_path = "logs/app.log"
max_file_size_mb = 10
backup_count = 5
enable_console = true