# .streamlit/secrets.toml
# DENSO Project Manager Pro - Secrets Configuration

# Production Server  
# [database]
# server = "10.73.148.27"
# database = "ProjectManagerDB"
# username = "TS00029"
# password = "Thammaphon@TS00029"
# driver = "ODBC Driver 17 for SQL Server"

# .streamlit/secrets.toml
# Configuration file for SDX Project Manager
# ⚠️ DO NOT COMMIT THIS FILE TO VERSION CONTROL

[database]
# SQL Server Configuration
server = "localhost\\SQLEXPRESS"  # หรือ "your-server-name"
database = "SDXProjectManager"
username = "your_username"        # หรือใช้ Trusted_Connection
password = "your_password"        # หรือใช้ Trusted_Connection
driver = "{ODBC Driver 17 for SQL Server}"
timeout = 30
pool_size = 5


[app]
# Application Settings
name = "SDX Project Manager"
version = "2.0.0"
debug = false
secret_key = "your-secret-key-here"  # สร้าง random string

[email]
# Email Configuration (ถ้าต้องการส่งอีเมล)
smtp_server = "smtp.gmail.com"
smtp_port = 587
smtp_username = "your-email@gmail.com"
smtp_password = "your-app-password"
from_email = "noreply@sdx.com"

[security]
# Security Settings
session_timeout = 28800  # 8 hours in seconds
max_failed_logins = 5
password_min_length = 8
require_complex_password = true

[features]
# Feature Flags
enable_notifications = true
enable_time_tracking = true
enable_file_attachments = true
enable_audit_log = true

# ============================================================================
# การตั้งค่าที่แนะนำ:
# ============================================================================

# 1. สำหรับ Development (ใช้ SQL Server Express LocalDB):
#    server = "(localdb)\\MSSQLLocalDB"
#    database = "SDXProjectManager" 
#    trusted_connection = "yes"

# 2. สำหรับ Production (ใช้ SQL Server):
#    server = "your-production-server"
#    database = "SDXProjectManager"
#    username = "sdx_app_user"
#    password = "secure_password"

# 3. สำหรับ Docker SQL Server:
#    server = "localhost,1433"
#    database = "SDXProjectManager"
#    username = "sa"
#    password = "YourStrong@Passw0rd"

# ============================================================================
# วิธีการใช้งาน:
# ============================================================================
# 1. คัดลอกไฟล์นี้ไปยัง .streamlit/secrets.toml
# 2. แก้ไขค่า database connection ให้ถูกต้อง
# 3. รัน: streamlit run app.py
# 4. เข้าสู่ระบบด้วย admin/admin123